server:
  port: 8080
  tomcat:
    basedir: tomcat
# log
logging:
    file: ./logs/cenpur-backend.log
    level:
        root: info
        com.platform: debug

spring:
    http:
        multipart:
            max-file-size: 1Mb
            max-request-size: 10Mb
    #JDBC Global Setting
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.82.12.164:3306/cenpur?useUnicode=true&characterEncoding=utf-8
        username: root
        password: sh@@@
        #DataSource Global Setting
        initialSize: 1
        minIdle: 1
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: false
        # druid StatVie
        statView:
            allow: 10.82.12.164
            deny:
            loginUsername: admin
            loginPassword: admin

    #mvc
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

    # REDIS (RedisProperties)
    redis:
        key-prefix: cenpur-backend
        host: localhost
        port: 6379
        password:
        timeout: 0
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        cluster:
          max-redirects: 5
          nodes: 10.82.12.72:6379,10.82.12.73:6379,10.82.12.74:6379

#dubbo
dubbo:
    application-name: cenpur-backend
    annotation-package: com.platform.modules
    protocol-name: dubbo
    protocol-port: 20881
    registry-protocol: zookeeper
    registry-address: 10.82.12.2:2181,10.82.12.135:2181,10.82.12.136:2181,10.82.12.137:2181,10.82.12.139:2181

#文件上传路径 空为系统默认配置
fileUploadPath: http://10.82.12.225/cenpur/cenpur-backend/uploads/
#文件服务器地址
fileAccessPath: http://10.82.12.225/cenpur/cenpur-backend/uploads/
#静态文件后缀
staticFileSuffix: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk
#动态文件后缀
urlSuffix: .html
#管理基础路径
adminPath: /a
#前端基础路径
frontPath: /f
#踢出之前登录的/之后登录的用户 默认踢出之前登录的用户
userKickoutAfter: false
#同一个帐号最大会话数 默认1
userMaxSession: 20
#是否不允许刷新主页，不允许情况下，刷新主页会导致重新登录
notAllowRefreshIndex: false
#单点登录CAS设置
casServerUrl: http://127.0.0.1:8180/cas
casProjectUrl: http://127.0.0.1:8080/a