server:
  port: 8888
  address: localhost
# log
logging:
    file: logs/platform.log
    level:
        root: info
        com.platform: info

druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/platform_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    #DataSource Global Setting
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: false
    # druid StatView
    statView:
        allow: 127.0.0.1
        deny:
        loginUsername: admin
        loginPassword: admin

spring:
    #mvc
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

    # REDIS (RedisProperties)
    redis:
        key-prefix: cenpur-backend
        host: localhost
        port: 6379
        password:
        timeout: 0
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0
        cluster:
          max-redirects: 5
          # nodes: localhost:6379
          nodes: 10.82.12.30:6379,10.82.12.30:6479,10.82.12.31:6379

#dubbo
dubbo:
    application-name: platform
    annotation-package: com.platform.modules
    protocol-name: dubbo
    protocol-port: 20880
    registry-protocol: zookeeper
    registry-address: 127.0.0.1:2181


#文件上传路径 空为系统默认配置
fileUploadPath: /Users/fengcheng/IdeaProjects/platform-boot/src/main/webapp/uploads/
#文件服务器地址
fileAccessPath: /uploads/
#静态文件后缀
staticFileSuffix: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk
#动态文件后缀
urlSuffix: .html
#管理基础路径
adminPath: /a
#前端基础路径
frontPath: /f
#踢出之前登录的/之后登录的用户 默认踢出之前登录的用户
userKickoutAfter: false
#同一个帐号最大会话数 默认1
userMaxSession: 2
#是否不允许刷新主页，不允许情况下，刷新主页会导致重新登录
notAllowRefreshIndex: false
#单点登录CAS设置
casServerUrl: http://127.0.0.1:8180/cas
casProjectUrl: http://127.0.0.1:8080/a
